### ISSUE TITLE
Build Rudimentary 3D Engine with JavaScript and SVG

### ISSUE THREAD

**Issue by matthiasak** [jsfest/sf-cfp#11]
3D engines are mystical unicorns – but they don't have to be shrouded in mystery. This talk covers some "DIY" beginners' magic behind 3D, so that you can create your own unicorns and rainbows.

The mobile market is especially ripe for some innovation, however. WebGL faces many performance issues right now in the mobile browser market. SVG, on the other hand, works on far more devices than WebGL, including most of the smartphones saturating the consumer market. 

I previously presented on this topic at HoustonJS Meetup, and would like to expand on the content.

At HoustonJS (http://houstonjs.com), I gave a talk on building a 3D engine with JavaScript and SVG:

http://www.meetup.com/houston-js/events/136589142/
http://vimeo.com/74150629
http://matthiasak.github.io/Building-a-Rudimentary-3D-Engine-with-SVG/

**Comment by mikeal** [comment]
I love the topic but your previous talk was 50+ minutes. Do you have any creative ideas that can trim it down to the necessary 20 minutes?

**Comment by matthiasak** [comment]
Absolutely. Instead of discussing the code in-depth, I figured I could provide a shortened version of the story behind it as well as a little less detail on the engine itself to keep things moving along.

Finally; it may be possible to setup a series of codepens instead of walking through the code so that the codepens would demonstrate on the screen what the steps of drawing are (less text, more visuals)

**Comment by mikeal** [comment]
+1

**Comment by boolpath** [comment]
:+1:

**Comment by mikeal** [comment]
This talk is accepted, you should be a collaborator on the speaker repo now. https://github.com/mikeal/jsfest-speakers
