### ISSUE TITLE
Adventures in Building a White-Label Web Platform with Node and Angular

### ISSUE THREAD

**Issue by NickHeiner** [jsfest/sf-cfp#61]
At Opower, we build a white-label product that is embedded into utility companies’ sites to help their consumers understand and [reduce their energy usage](http://blog.opower.com/2013/10/feel-the-momentum-opower-surpasses-3-billion-kilowatt-hours-of-energy-savings/). Our legacy web app is a giant Java/Spring monolith. It worked for a while, but soon started running into scaling concerns with our ability to customize our product to fit our clients’ needs.

To solve the problem, we’re building a new system in Node and Angular, with help from Grunt, Yeoman, Sass, Browserify, and (previously) Bower. Instead of a monolithic set of JSPs, we provide an sdk that lets anyone build a widget without knowing anything about how the general Opower tech stack works. I would like to: 
- Explain our system’s architecture and the challenges we’ve faced building it.
- Tell the story of our evolution from a bower-centric deploy system to an npm/browserify-centric one. 
- Describe the challenges of isolating js and css components from one another on the page, and talk about the solutions we’ve found.
- Discuss the benefits of taking advantage of npm’s affordance for composing a system out of many tiny, focused modules

(I can cut that down if it doesn’t fit in 20 minutes.)

I find this to be a really interesting set of problems and it would be fun to share my team’s experiences with a larger audience. I can provide more detail as necessary.

**Comment by devorbitus** [comment]
I would love to hear about your experiences as we are starting to go down that route ourselves.

**Comment by developer0116** [comment]
Can you elaborate the project architecture?

**Comment by NickHeiner** [comment]
The project architecture is 7 years old at this point, and I wouldn't recommend anyone do it who is starting anew in today's world. Thanks for your interest! :smile:
